# Generated by Django 4.2.9 on 2024-01-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finstagramapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
