# Generated by Django 4.2.9 on 2024-01-30 20:41

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("finstagramapp", "0002_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("num_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
