# Generated by Django 4.2.9 on 2024-01-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finstagramapp", "0003_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
