# Generated by Django 4.2.9 on 2024-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finstagramapp", "0004_post_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="num_likes",
            field=models.IntegerField(default=1),
        ),
    ]
