# Generated by Django 4.2.9 on 2024-01-31 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("finstagramapp", "0006_alter_post_num_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
