# Generated by Django 4.2.9 on 2024-02-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finstagramapp", "0008_likepost_alter_post_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower", models.CharField(max_length=100)),
                ("following", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="num_followers",
            field=models.IntegerField(default=0),
        ),
    ]
